import { describe, expect, it } from "vitest";
import { buildApp } from "../src/server.js";
import type { EngineRunner } from "../src/types.js";

const validBody = { question: "这项合作该继续吗？", questionType: "decision", datetime: "2026-09-09T10:30:00+08:00", timezone: "Asia/Kuala_Lumpur", city: "Kuala Lumpur", longitude: 101.6869, trueSolar: false };
function runner(stdout = JSON.stringify({ ok: true, time: "2026-09-09T10:30:00+08:00", summary: "阳遁六局", prompt: "prompt" })): EngineRunner { return { run: async () => ({ stdout, stderr: "", exitCode: 0 }) }; }
describe("casting API", () => {
  it("returns health status", async () => { const app = buildApp({ binaryPath: process.execPath }); const response = await app.inject({ method: "GET", url: "/health" }); expect(response.statusCode).toBe(200); expect(response.json().engineAvailable).toBe(true); await app.close(); });
  it("rejects invalid question", async () => { const app = buildApp({ binaryPath: "test", runner: runner() }); const response = await app.inject({ method: "POST", url: "/cast/qimen", payload: { ...validBody, question: "" } }); expect(response.statusCode).toBe(400); expect(response.json().error.code).toBe("INVALID_INPUT"); await app.close(); });
  it("rejects invalid method", async () => { const app = buildApp({ binaryPath: "test", runner: runner() }); const response = await app.inject({ method: "POST", url: "/cast/unknown", payload: validBody }); expect(response.statusCode).toBe(400); expect(response.json().error.code).toBe("INVALID_METHOD"); await app.close(); });
  it("normalizes a successful mocked engine spawn", async () => { const app = buildApp({ binaryPath: "test", runner: runner() }); const response = await app.inject({ method: "POST", url: "/cast/qimen", payload: validBody }); const body = response.json(); expect(response.statusCode).toBe(200); expect(body.success).toBe(true); expect(body.summary).toBe("阳遁六局"); expect(body.raw.longitude).toBe(101.6869); expect(body.raw.trueSolar).toBe(false); await app.close(); });
  it("preserves a Chinese UTF-8 question unchanged through the engine runner", async () => { const question = "测试线上奇门排盘是否正常"; let receivedQuestion = ""; const capture: EngineRunner = { run: async (_bin, args) => { receivedQuestion = args[args.indexOf("-q") + 1]; return { stdout: JSON.stringify({ ok: true, time: validBody.datetime, summary: "ok" }), stderr: "", exitCode: 0 }; } }; const app = buildApp({ binaryPath: "test", runner: capture }); const response = await app.inject({ method: "POST", url: "/cast/qimen", payload: { ...validBody, question } }); expect(response.statusCode).toBe(200); expect(receivedQuestion).toBe(question); await app.close(); });
  it("requires an explicit datetime in production remote mode", async () => { const app = buildApp({ binaryPath: "test", runner: runner(), requireDatetime: true }); const response = await app.inject({ method: "POST", url: "/cast/qimen", payload: { ...validBody, datetime: null } }); expect(response.statusCode).toBe(400); expect(response.json().error.code).toBe("DATETIME_REQUIRED"); await app.close(); });
  it("preserves Kuala Lumpur metadata and keeps engine time distinct", async () => { const requested = "2026-09-09T05:02:00+08:00"; const engineTime = "2026-09-09T05:02:00+08:00"; const app = buildApp({ binaryPath: "test", runner: runner(JSON.stringify({ ok: true, time: engineTime, summary: "ok" })), requireDatetime: true }); const response = await app.inject({ method: "POST", url: "/cast/qimen", payload: { ...validBody, datetime: requested } }); const body = response.json(); expect(body.requestedCivilDatetime).toBe(requested); expect(body.timezone).toBe("Asia/Kuala_Lumpur"); expect(body.longitude).toBe(101.6869); expect(body.engineCastTime).toBe(engineTime); expect(body.raw.requestedCivilDatetime).toBe(requested); await app.close(); });
  it("reports malformed engine JSON", async () => { const app = buildApp({ binaryPath: "test", runner: runner("not json") }); const response = await app.inject({ method: "POST", url: "/cast/qimen", payload: validBody }); expect(response.statusCode).toBe(502); expect(response.json().error.code).toBe("MALFORMED_ENGINE_OUTPUT"); await app.close(); });
  it("maps true solar and longitude into command arguments", async () => { let args: string[] = []; const capture: EngineRunner = { run: async (_bin, received) => { args = received; return { stdout: JSON.stringify({ ok: true, summary: "ok" }), stderr: "", exitCode: 0 }; } }; const app = buildApp({ binaryPath: "test", runner: capture }); await app.inject({ method: "POST", url: "/cast/qimen", payload: { ...validBody, trueSolar: true, longitude: 101.6869 } }); expect(args).toContain("--lon"); expect(args).toContain("101.6869"); expect(args).not.toContain("--no-truesolar"); await app.close(); });
  it("maps the exact RFC3339 datetime to the confirmed --time CLI argument", async () => { let args: string[] = []; const capture: EngineRunner = { run: async (_bin, received) => { args = received; return { stdout: JSON.stringify({ ok: true, time: validBody.datetime, summary: "ok" }), stderr: "", exitCode: 0 }; } }; const app = buildApp({ binaryPath: "test", runner: capture, requireDatetime: true }); await app.inject({ method: "POST", url: "/cast/qimen", payload: validBody }); expect(args[args.indexOf("--time") + 1]).toBe("2026-09-09T10:30:00+08:00"); expect(args).toContain("--no-truesolar"); await app.close(); });
  it("returns a timeout response", async () => { const timeoutRunner: EngineRunner = { run: async () => { const { EngineTimeoutError } = await import("../src/engine.js"); throw new EngineTimeoutError("timeout"); } }; const app = buildApp({ binaryPath: "test", runner: timeoutRunner }); const response = await app.inject({ method: "POST", url: "/cast/qimen", payload: validBody }); expect(response.statusCode).toBe(504); expect(response.json().error.code).toBe("ENGINE_TIMEOUT"); await app.close(); });
});
