import type { CastRequest, Chart, Method } from "@/lib/types";
import { sampleChart } from "@/lib/mock-data";
import { normalizeQimenEngineResult } from "@/lib/qimen-normalizer";

export interface CalculationEngine { readonly method: Method; cast(request: CastRequest): Promise<Chart>; }
interface RemoteResponse { success: boolean; engine?: string; method?: Method; castTime?: string; summary?: string; raw?: Record<string, unknown>; error?: { code?: string; message?: string }; }
export class CastingApiError extends Error { constructor(message: string, public readonly code?: string) { super(message); } }
class MockEngine implements CalculationEngine { constructor(public readonly method: Method) {} async cast(): Promise<Chart> { if (this.method === "qimen") return structuredClone(sampleChart); return { kind: this.method, ruleset: "mock-ruleset-v1", rawSummary: `Mock ${this.method} chart; replace this adapter with the external engine response.`, payload: { status: "mock" } }; } }
class RemoteEngine implements CalculationEngine { constructor(public readonly method: Method) {} async cast(request: CastRequest): Promise<Chart> { const response = await fetch(`/api/cast/${this.method}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: request.question, questionType: request.questionType, datetime: request.castTime, timezone: request.timezone, city: request.location, longitude: request.longitude ?? 101.6869, trueSolar: request.useTrueSolarTime }) }); const data = await response.json() as RemoteResponse; if (!response.ok || !data.success) throw new CastingApiError(data.error?.message ?? "远程排盘服务暂时不可用，请稍后重试。", data.error?.code); const base = { ruleset: "zhouyi-divination", rawSummary: data.summary ?? "排盘完成", raw: data.raw }; if (this.method === "qimen") return { kind: "qimen", ...base, ...normalizeQimenEngineResult(data.raw?.engineResult) }; return { kind: this.method, ...base, payload: data.raw ?? {} }; } }
export function getEngine(method: Method): CalculationEngine { return process.env.NEXT_PUBLIC_CASTING_MODE === "remote" ? new RemoteEngine(method) : new MockEngine(method); }
